### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by MichaBrugger** [XSPGMike/braincache_obsidian#2]
Hey there! I've just stumbled over braincache and I really like where you're taking this. I've been working on a very similar application lately (flashcards, chrome extension, obsidian integration, etc). Would you be interested in working on it together?

**Comment by XSPGMike** [comment]
hi, thanks, let's chat about it, I believe we are in the same TZ, if you are up to it we can hop on a call next week. ping me on discord :)
